name: BuildNRelease

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Build docker image
        run: |
          docker build --no-cache -t pioimage .

      - name: Build and publish ram usage
        run: |
          docker run --entrypoint /entrypointRelease.sh -e "GISTS_TOKEN=${{ secrets.GISTS_TOKEN }}" --rm pioimage
