name: Test

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Build docker image
        run: |
          docker build --no-cache -t 5bcf4108 .
      - name: Start container and test
        run: |
          docker run --rm 5bcf4108